server:
  port: 8088
demo: 
  test: pro
spring:
  application:
    name: config-cloud
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/  