server:
  port: 8090
demo: 
  test: local
# spring:
#   application:
#     name: config-client
# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/  
management:
  endpoints: 
      web: 
        exposure:
          include: health, info, refresh